function params = preset(name)
%LAMBERTPROJ.PRESET Return projection parameter presets.
%
%   params = lambertproj.preset("lambert93")
%   params = lambertproj.preset("repo_custom")

    arguments
        name (1,1) string
    end

    switch lower(strtrim(name))
        case "lambert93"
            % Official Lambert-93 definition for metropolitan France.
            params = struct( ...
                'name', 'Lambert-93', ...
                'falseEasting', 700000.0, ...
                'falseNorthing', 6600000.0, ...
                'latitudeOfOrigin', 46.5, ...
                'centralMeridian', 3.0, ...
                'standardParallel1', 44.0, ...
                'standardParallel2', 49.0, ...
                'semiMajorAxis', 6378137.0, ...
                'flattening', 1 / 298.257222101);

        case {"repo_custom", "original_repo", "custom"}
            % Parameters currently used in the original repository.
            params = struct( ...
                'name', 'Original repo custom Lambert projection', ...
                'falseEasting', 500000.0, ...
                'falseNorthing', 500000.0, ...
                'latitudeOfOrigin', 65.0, ...
                'centralMeridian', -19.0, ...
                'standardParallel1', 64.2500, ...
                'standardParallel2', 65.7500, ...
                'semiMajorAxis', 6378137.0, ...
                'flattening', 1 / 298.257222101);

        otherwise
            error('lambertproj:UnknownPreset', ...
                'Unknown preset "%s". Use "lambert93" or "repo_custom".', name);
    end
end
